### ISSUE TITLE
jexiftoolgui_with_jre doesn't start on Windows

### ISSUE THREAD

**Issue by spitzlbergerj** [hvdwolf/jExifToolGUI#109]
Hi,
unfortunately the jexiftoolgui does not start on my Windows and I can not find a solution.

I have jExifToolGUI-1.8.1.0-win-x86_64_with-jre downloaded on my Windows 10 machine. I have also downloaded the exiftool exiftool-12.18.zip. Both I have unpacked into the same directory.

As soon as I start jExifToolGUI, a message appears that the exiftool could not be found. I specify the path (= path of jExifToolGUI). After that nothing more happens.

In the logs directory there are log files with always the same content: [jexiftoolgui_20210214-0911.log](https://github.com/hvdwolf/jExifToolGUI/files/5977180/jexiftoolgui_20210214-0911.log)

I have already deleted the directory C:\Users\USERNAME\jexiftoolgui_data and all downloads several times and started all from scratch. But nothing changes.

Where can the error be? What else can I try?

Thanks a lot!

Josef

**Comment by hvdwolf** [comment]
From the log I see
`09:11:36.432 [AWT-EventQueue-0] ERROR o.h.j.controllers.CommandRunner - IOException error
java.io.IOException: Cannot run program "-k version": CreateProcess error=2, Das System kann die angegebene Datei nicht finden`

It means that you use the "exiftool-k.exe" version, which you should rename to "exiftool.exe" as is described on the Releases page.

Maybe I will add an extra check so that a popup is generated to tell users to rename the "exiftool-k.exe" version

**Comment by spitzlbergerj** [comment]
Thank you very much. This is how it works.
And sorry for posting the issue, although even more intensive reading of the documentation would have helped. I was really stumped though.
