### ISSUE TITLE
jExifToolGUI will not launch

### ISSUE THREAD

**Issue by carolwhite725** [hvdwolf/jExifToolGUI#122]
I've been trying to install what looks to be a very useful tool; jExifToolGUI app on an old MacBook running Big Sur. I have read most of the issues with mac but haven't seen Big Sur yet. I've changed a bunch of permissions; probably too many, Updated Java, downloaded and installed jExifToolGUI-x86_64-macos-1.7.3-with_jre (and without).dmg trashed several times but still seem to get the same error when trying to launch from the terminal and it is: java.io.IOException: Cannot run program "/Users/MyMachine/exiftool-path": error=13, Permission denied. I have more logs if it is appropriate under guidelines to supply.

Right now, I am turning in and hope you can respond.

**Comment by hvdwolf** [comment]
I am very sorry. I somehow missed this issue completely.

Please give the exact path where you have exiftool installed.
Is the complete path "/Users/MyMachine/exiftool-path/exiftool"?
And what happens if you open a terminal and try to start exiftool from that location with "/Users/MyMachine/exiftool-path/exiftool", or whatever the path is.

**Comment by Tiger-AC** [comment]
I have a very similar issue whereby the attempted initial launch of this app resulted in opening a java icon and shows the following text when clicking on it:
/Applications/jExifToolGUI.app/Contents/MacOS/jre/Contents/Home/bin/java ; exit;
Usage: java [options] <mainclass> [args...]
           (to execute a class)
   or  java [options] -jar <jarfile> [args...]
           (to execute a jar file)
   or  java [options] -m <module>[/<mainclass>] [args...]
       java [options] --module <module>[/<mainclass>] [args...]
           (to execute the main class in a module)
   or  java [options] <sourcefile> [args]
           (to execute a single source-file program)
.......................................................

After that, nothing happened. I tried to run the app directly from the terminal by typing the following command:
/Applications/jExifToolGUI.app/Contents/MacOS/jre/Contents/Home/bin/java /Applications/jExifToolGUI.app/Contents/MacOS/jExifToolGUI.jar 

Error: Could not find or load main class .Applications.jExifToolGUI.app.Contents.MacOS.jExifToolGUI.jar
Caused by: java.lang.ClassNotFoundException: /Applications/jExifToolGUI/app/Contents/MacOS/jExifToolGUI/jar

I then went to Oracle webpage and downloaded the latest Javiers SE Development Kit 17. After successfully installed it and double clicked on jExifToolGUI.jar , it generated a log file 
(https://github.com/hvdwolf/jExifToolGUI/files/7198540/jexiftoolgui_20210921-0557.log)
and still nothing happened.

PS. The exiftool was installed prior to jExifToolGUI and it can be launched in any directory in terminal.

**Comment by hvdwolf** [comment]
The log in your post above says something else, but the log you added makes it quite clear:
`java.io.IOException: Cannot run program "/Users/imac/Downloads/ExifTool-12.30.dmg": error=13, Permission denied`
You did not open the exiftool dmg and you did not install exiftool. Once that is done, JTG will run fine.

**Comment by Tiger-AC** [comment]
Thanks for the reply. The"/Users/imac/Downloads/ExifTool-12.30.dmg" is there and have already run once before (installation).
I finally got it going by typing "sudo java -jar /Applications/jExifToolGUI.app/Contents/MacOS/jExifToolGUI.jar". This "java" is the one I downloaded and installed from Oracle directly. And this "sudo" is also very important: it would not run without it.

**Comment by hvdwolf** [comment]
Yes, but you try to use the exiftool inside the opened exiftool.dmg instead of the exiftool binary which has been installed in /usr/local/bin. After reboot or proper user action to unmount the exiftool.dmg, JTG can't access exiftool inside the dmg. sudo will then open the dmg when required.
Please check your preferences to see which exiftool JTG is trying to use.
Secondly: the sudo command is NOT necessary. Only when exiftool is installed in a location where a normal user does not have access to, or JTG is installed in a location a normal user does not have access to.
I would very seriously advice against using sudo with JTG. I do not want "my programs" to have access to all system resources: that is how I write them. Again: check your preferences.
