### ISSUE TITLE
Question: Do you like some help?

### ISSUE THREAD

**Issue by Swissbite** [hvdwolf/jExifToolGUI#2]
Hi @hvdwolf 
I just saw your new project using Java as the new Exif Tool GUI. First of all: Congratulations on your decision. It will be a lot of work to rewrite your old but good product.

My question is: Do you like some help/support? I'm a software engineer using Java / Kotlin all my day, and I could help you structure the project in a maintainable way. I'm sure, you are able to do it all by yourself, but if I could help to support you in a tool I like to use for myself, then I would like to participate.

I don't to just fork and make changes you would never approve, I would like to help you as good as I can to make this software useful and usable.

**Comment by hvdwolf** [comment]
Hi,

Yes, I'm open to any help. As you can see I am only a beginning java programmer who involuntarily started programming java little over a year ago as I needed something nobody else "volunteered" to program. So as usual in Open Source, you start doing it yourself.

However, a week ago I accidently stumbled on [FastPhotoTagger](http://fastphototagger.sourceforge.net/). I already had a couple of mails back and forth with that developer. His tool is far more mature than mine. 
On the other hand: My tool has a slightly different approach which I still consider useful (Extra menu and the geotagging). I'm just back from a 3 days holiday where I extensively used geotagging from my own tool.
I want to discuss "my requirements" with him. If he is open to that I might join his development and stop mine. If not, I will continue my own.
And of course: If you think his tool is more worthwile to continue working on, you're free to do so.

And otherwise, like I already mentioned: I'm open to any help.
