### ISSUE TITLE
Edit data > copy from selected image = NOK

### ISSUE THREAD

**Issue by mrtngrsbch** [hvdwolf/jExifToolGUI#201]
The data editing tab does NOT import all image data.

https://user-images.githubusercontent.com/693328/144783359-dd55eb6f-b91d-4f77-aa29-08c7e1da02d0.mp4

sample image:
![IMG_9173-Molinos-de-viento1](https://user-images.githubusercontent.com/693328/144783384-ab0dedb3-da52-4ad4-8e5e-6556ea49343d.jpg)

**Comment by hvdwolf** [comment]
Sorry, but I really don't understand. 
The edit screen shows the default value in the most right column. If you copy from another image, it will not change the default value. Did you also save to another image and had a look at the values?

Maybe a 4-column view should be displayed in the "Edit data" so that you see what you copied next to the default value.

**Comment by mrtngrsbch** [comment]
Sorry... maybe this video is a better example.
Metadata that exists in an image is not copied when I want to edit it

https://user-images.githubusercontent.com/693328/144938579-4a854258-e43d-4a1a-a2da-4d376b617f1b.mp4

**Comment by hvdwolf** [comment]
I will have to look at this.
I did have an extremely busy last week and still 2 days to go next week.
I will pick up after that.

**Comment by sossw** [comment]
Hi hvdwolf,  I've sent you a pull request for your consideration as a possible fix for this issue.  Regards.

**Comment by hvdwolf** [comment]
@sossw : Sorry. I forgot to say thank you, but I added you to the credits. I will also see if I can use your idea in other locations.

**Comment by sossw** [comment]
No problem :)  Thanks for adding me to the credits.
