### ISSUE TITLE
Thanks for version 1.8.1 - sad to be unable to upgrade

### ISSUE THREAD

**Issue by matteg** [hvdwolf/jExifToolGUI#252]
This is not an issue for anyone but me and the other 37 % of java users who choose to continue using Java 8.
See https://www.infoworld.com/article/3652408/java-8-still-dominates-but-java-17-wave-is-coming-survey.html 

Apparently the ability to support TIFF format graphics is more important than we are.  Is there no way to support Java 8 - I have not used that file format in decades and would be happy to accept the lack of support for TIFF format graphics.

I will continue to use my version 1.8.1

**Comment by hvdwolf** [comment]
Whatever operation system you are, you can also download a version with java-11 included.
I really don't understand the resistance.
Another java version as packaged with my JTG, takes 125-145 MB. This is so small compared with the Gigabytes of photos I have and most other photographers. Some use tiff images of 30-150MB, already more than the the entire JRE.
Even with a small SSD (64GB for example) another 125-145MB means nothing.
It is not only tiff. There are more code changes that work more efficient and faster with java-11.

And why stay on java-8? Are you using Windows XP or older?
Does it mean you use old java apps that are not supported with java versions newer than java-8? Why not aks that developer to finally update his/her software after 8 years.

So, no downgrade to a java version that is no longer supported since 2014.

**Comment by matteg** [comment]
I am not resisting upgrading to Java-11.  I believe that neither are the 37% of current java users.

As Java-8 evolved to higher levels those who are steering the evolution chose to deprecate and remove critical functions that experienced java developers .... especially those who have experience working for large diversified organistions discovered that Java-9 and subsequent versions no longer could support the java server functionality essential to our work.

The concurrent emergence of OpenJDK allowed us to choose to continue to use Java-8 as our primary tool - thereby avoiding being forced by others to spend considerable time and effort learning how to fix a problem imposed on us by others.

My generation of developers believes in co-operation and compliance with standards.  However, many of us (currently 37%)  are unwilling to be forced to adopt new technology we have no need of - even though it may be more efficient.

In my case, I considered java versions 9 and 10 to be downgrades.  I stopped paying attention after that since those charting the course of java versions show no hesitation to removing language features without  any concern for those of us who have spent careers developing in java.

When a future java version removes critical functions that you depend on, I hope you will remember these words.  That future is now in your hands.  Please show more empathy and respect for others as you gain more life experience.

**Comment by hvdwolf** [comment]
I am 59 and have been contributing to Open Source since 1993 on very many areas (more than 50 projects). I think I gained some life experience already.
I was forced to switch to java after the python-pyside combination I used was no longer supported nor upgraded, even though I had no need for other functionality or those upgrades. Just like you describe for java-8 (And since 1½ year PySide has been brought to life again, but so be it).

So with regard to empathy: It has nothing to do with empathy. (For me) it has to do with spending more than 10 years on python and being flexible enough to switch to something completely different and spend the time to learn that.
For me it has to do with lack of flexibility of your generation of programmers not willing to move forward and getting out of their comfort zone. I think I am of the exact same generation and maybe older, but I am willing to adapt, but not back in time.

**Comment by matteg** [comment]
I never stopped learning - and hopefully continue to do so.  For me there was a time in my life when I realised that time spent learning technology was time not spent enjoying my children and grandchildren.  As my body and mind became less capable I came to realise that I needed to balance my time more wisely.

When others attempt to force me to spend time adapting to their priorities in life I no longer react with anger and/or sadness that others believe it's ok to treat people that way.

With respect, your comments repeatedly seem to be only considering the world from your personal perspective.  I am much older than you but perhaps a little wiser (hoping to become wiser anyway).  I'm not sure this conversation was evidence of a step forward or back for me.

Good luck with your life journey.
