### ISSUE TITLE
Tiff images don't show preview

### ISSUE THREAD

**Issue by mrtngrsbch** [hvdwolf/jExifToolGUI#37]
Hi,

TIFF image thumbnails

 are not shown

![ScreenShot 2020-07-24 a la(s) 15 51 30](https://user-images.githubusercontent.com/693328/88425596-0471b180-cdc6-11ea-8338-a708691c0365.jpg)

best,
Martin
jExifToolGUI 1.3.0
OSX 10.15.5
Java 8 Update 261

**Comment by hvdwolf** [comment]
Can you share one of the images?
Tif images can only be displayed if they contain some preview.

**Comment by hvdwolf** [comment]
Fixed in version 1.4

Tif(f) files were not previewed. They are now differently handled based on java version.
* tiff images **with** preview/thumbnail images inside are displayed (this was already working).
* tiff images **without** preview/thumbnail inside can only be displayed on java V11 or higher. Use a "full jre" version (comes with V11) or install V11 or newer.
