### ISSUE TITLE
Setting Lang in Preferences

### ISSUE THREAD

**Issue by mrtngrsbch** [hvdwolf/jExifToolGUI#49]
Hi,

Is it possible to add a language option in the preferences panel?

best,
Martin
OSX 10.15.5
jExifToolGUI 1.4.2
openjdk 11.0.8

**Comment by hvdwolf** [comment]
You mean a language for the application, so that it displays in English or Spanish or German or in whatever language the application already has been translated?
That should be possible but I did not look into it yet. It will of course require that the app is already translated in that language.

And to be sure: You do not mean the current option in Preferences where you can select the language of the tag names/descriptions (as far as Exiftool supports that language)?

**Comment by mrtngrsbch** [comment]
I mean the whole GUI in general, not just "Language to use to display
metadata"
The problem is that I can't see my GUI in Spanish and I suppose that for
deadly users it will also be a problem

Estoy avanzando bien con la traducción pero necesitaría ver la
traducción actual en la GUI, mismo que no esté terminada aunI am making
good progress with the translation but I would need to see the current
translation in the GUI, even if it is not finished yet. There are several
translations that cannot be translated literally and even in English the
concept is complex

Martin GERSBACH
Responsable de Operaciones
mg@museosabiertos.org
www.museosabiertos.org

**Comment by hvdwolf** [comment]
It is now possible to change a language in the Preferences in the Language tab.
Of course only the languages  for which the app has been translated, and English is available.
to be released in 1.5

**Comment by mrtngrsbch** [comment]
so many changes these days that that email got old


Martin GERSBACH
Responsable de Operaciones
mg@museosabiertos.org
www.museosabiertos.org
