### ISSUE TITLE
Does not build anymore

### ISSUE THREAD

**Issue by zoe12345** [hvdwolf/jExifToolGUI#55]
Very recently (a few days), does not compile anymore. You can see log here :
https://pastebin.com/BREPCyFz
Last successfull compile was on tuesday 04th august 2020 22:39:54
My java is :
java-11-openjdk

**Comment by hvdwolf** [comment]
I am working on it. I am about to release a 1.5, but these are already "exercises" for 1.6.
In my local repository it has already been corrected.

**Comment by hvdwolf** [comment]
Additional to this there is a real dirty hack to add all META.INF Spi descriptions from the TwelveMonkeys library. This is due to a bug in both the fatJar gradle functionality, as well as the shadowJar functionality.
You will not be able to catch/include that in a normal build.
I am still searching for the correct kotlin syntax to have that scripted in the build.gradle.kts

Actually I now use a "post build" step to add those to the jar.
The TwelveMonkeys/META-INF folder is in the repo. I zip them into the `jExifToolGUI-all.jar` , which I already have renamed and copied to my main jExifToolGUI folder, and do that from the TwelveMonkeys to keep the paths in the jar correct..

```
cd TwelveMonkeys
zip ../jExifToolGUI.jar META-INF/services/*
cd ..
` ``
What I want to script in the build itself is not even described in the official documentation. It is for the old "groovy" build.gradle, but not for the new kotlin build.gradle.kts.

Of course it is high on my list to still bring this in the build.gradle.kts, but currently do not see an option.

**Comment by hvdwolf** [comment]
I removed/disabled all "pre 1.6" stuff. 
It should now compile again, be it that you need to the the last zip step to create a really functional jar supporting tif/pgm/pict etc.

**Comment by hvdwolf** [comment]
I made a very stupid mistake. I forgot to add the locales to the repo. Locally the builds fine and runs fine unless you go into Preferences. I do a fresh pull and see if ti builds, but that worked fine.
So now I did a 1.5.1 source code release. You need that one for Aur builds.
