### ISSUE TITLE
Rare 'open folder' behavior

### ISSUE THREAD

**Issue by mrtngrsbch** [hvdwolf/jExifToolGUI#65]
Hi,
'Open folder' does not work as it should...
see video in zip file

[ScreenShot 2020-09-19 a las 14.16.59.mp4.zip](https://github.com/hvdwolf/jExifToolGUI/files/5250257/ScreenShot.2020-09-19.a.las.14.16.59.mp4.zip)

best,
Martin
OSX 10.15.5
jExifToolGUI 1.6.0-RC2
openjdk version "11.0.8" 2020-07-14

**Comment by hvdwolf** [comment]
This is due to the AWT Filedialog.
The AWT Filedialog looks really native on MacOS, but can't be limited to files_only, directories_only or files_and_directories. It is always in files_and_directories. This sometimes gives issues.
The jfilechooser on the other hand does not look native at all on MacOS but can be set to directories_only.
