### ISSUE TITLE
images count [feature request]

### ISSUE THREAD

**Issue by mrtngrsbch** [hvdwolf/jExifToolGUI#66]
HI,

I think it would be interesting to have an image counter... ;-)

![ScreenShot 2020-09-19 a las 14 27 54](https://user-images.githubusercontent.com/693328/93681815-bb1ba680-fa84-11ea-9857-c6999a32cbfb.jpg)

best,
Martin
OSX 10.15.5
jExifToolGUI 1.6.0-RC2
openjdk version "11.0.8"

**Comment by mrtngrsbch** [comment]
Hi,

Haciendo unas pruebas descubro que es muy importante tener un contador de imágenes...
He 'abierto' 1691, pero al momento de escribir datos en ellas, me doy cuenta que en realidad son 488

![ScreenShot 2020-09-19 a las 14 33 40](https://user-images.githubusercontent.com/693328/93684828-d509b900-fa85-11ea-9d8b-e084cb519a0d.jpg)


see log in zip file
[jexiftoolgui_20200826-1223.log.zip](https://github.com/hvdwolf/jExifToolGUI/files/5250289/jexiftoolgui_20200826-1223.log.zip)


best,
Martin
OSX 10.15.5
jExifToolGUI 1.6.0-RC2
openjdk version "11.0.8"

**Comment by hvdwolf** [comment]
The log file does not mention much. I guess you did not chose a high log level.

I created the "loaded files" counter. Will be in 1.6.0

**Comment by hvdwolf** [comment]
I closed it too soon. It says feature request but also mentions that not all files are treated.
So, still the issue when selecting 1600+ files where only 488 are updated, is not solved.

It "might" be an issue with the files, but actually I think it is with memory buffers, either in the shell or in java.

My program works with selecting images. Even if you load a directory, it still continues with selecting (all) images.
I never intended my program to work on 1600+ images.

Exiftool also has a directory mode, where you don't specify a set of images, but simply a folder. In that case you can use as many files as your system supports.
But that would really require a major change on  low-level in my program. 
The logic as such is not difficult: 
(user selects folder) AND (user then selects all loaded files inside the interface) => use a `DIR` command instead of a `<image1 image2 image3 ...>` command.
Changing that in the entire program flow through all sub-screens and sub-functions, is simply a very big task.

**Comment by mrtngrsbch** [comment]
Hi,

Version 161 no longer has this problem...
I have successfully opened and recorded 1683 files in both JFilechooser and Awt file dialog without problems
 ;-)

![image](https://user-images.githubusercontent.com/693328/94488777-a42e3000-01b9-11eb-9d67-2e6e61a2acda.png)


That if... unfortunately, the option "Load directory" does not work OK in my OSX 10.15.7 ;-(

best
