### ISSUE TITLE
Strange menu behavior in OSX

### ISSUE THREAD

**Issue by mrtngrsbch** [hvdwolf/jExifToolGUI#85]
Hi,

Menu is decoupled and interposed with other applications
see video in zip file

[ScreenShot 2020-11-11 a las 13.52.03.mp4.zip](https://github.com/hvdwolf/jExifToolGUI/files/5525497/ScreenShot.2020-11-11.a.las.13.52.03.mp4.zip)

best,
Martin
OSX 10.15.7
jExifToolGUI 1.7.0
openjdk version "11.0.8"

**Comment by hvdwolf** [comment]
I know. I have seen it before. MacOS has a completely different menu structure than other OSes. It integrates the programs menu with system options, whereas all other OSes separate this.  And because MacOS has become java unfriendly (and python and perl unfriendly), I currently can't integrate it anymore. The special MacOS code for this to work is in the application. But it no longer functions.

I still use java 8 as base level though (11 behaves the same as 8). I will check with higher java versions. Maybe there is a new workaround in java 14 or 15 . I did not check that yet.

**Comment by hvdwolf** [comment]
Menu integration is working. I searched and searched again. It is very, very crucial where you place the code. so I did about 10 placements and 10 compiles and then it worked. I thought it was as easy as mentioning it just before the screen was opened (and in theory it is)

[MacOSMenuIntegration.zip](https://github.com/hvdwolf/jExifToolGUI/files/5531243/MacOSMenuIntegration.zip)

**Comment by mrtngrsbch** [comment]
I am very sorry that OSX is a particular annoyance, but this problem was a particular stumbling block.
Thank you very much for paying attention to OSX ;-)
When my MacBookPro decides to suicide, I'll switch to Linux desktop

best

**Comment by hvdwolf** [comment]
If you like MacOS, then stay with it.
I have had macbook pros for about 5-6 years, unless I was completely fed up with Steve Job's world view which he actually really stated that way: "I want the iMac (and before that the failed Mac)  to be not compatible with anything else". And still the rest of the world tries to be compatible with Apple.
Even my daughter who has had 2 Macbooks now switched to Linux (also because Linux is now user friendly and it was not 10 years ago).

**Comment by mrtngrsbch** [comment]
hehe...
Sincerely, OSX (Mac OS /X;-) is very good, but day by day it gives me more irritation.
I've been using Linux for +20 years, mainly on server. If I haven't switched to Linux yet, it's because of some applications that make my day easier and that don't exist in Linux, like Adobe Lightroom.
But the luck is already out. My next computer will be Lenovo/Dell + Ubuntu, with OSX in a VM

**Comment by hvdwolf** [comment]
released in 1.7.1.
Fixes the issue and finally integrates the program menu into the Apple system menu
